title = "Jérôme Pin - Jardin Numérique"

# The URL the site will be built for
base_url = "https://notes.jeromepin.fr"

default_language = "fr"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "even"

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
even_menu = [
    {name = "Home", url = "/"},
    # {name = "Search", url = "search"},
    {name = "Tags", url = "/tags"},
]